### ISSUE TITLE
OpenUDID is not unique across devices

### ISSUE THREAD

**Issue by jamesrz2live** [ylechelle/OpenUDID#17]
Suppose that a user has your application installed on device A. The user then buys a new device, device B. The user creates a backup of device A using iTunes and then restores it onto device B. 

When the user launches your application on device B, it will report the same udid as device A because this information is read from NSUserDefaults (which was copied from device A to B during the backup/restore).

**Comment by ylechelle** [comment]
This scenario is indeed possible.

Here, this calls for a signature that uses the MAC address to sign and compare with former, and regenerate the OUDID in that case. Makes sense?

**Comment by dgutzeit** [comment]
+1 for this approach

**Comment by patoth** [comment]
+1, just make sure former OUDID generated with past versions remains the same.

**Comment by Gavtron** [comment]
+1, and I'm curious when this change is going to be made, because nothing's been done with it for a few days and this seems pretty important

**Comment by ylechelle** [comment]
@gavtron  Feel free to suggest the code for it with a pull request. Otherwise, I should be able to address this by the end of the week...

**Comment by brody2consult** [comment]
There is already a nice solution, based on the MAC address by itself or in combination with the bundle ID at: https://github.com/gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5

**Comment by brody2consult** [comment]
I also found https://code.google.com/p/objc-guid/ and http://stackoverflow.com/questions/427180/how-to-create-a-guid-uuid-using-the-iphone-sdk

**Comment by ylechelle** [comment]
Chris,

Sorry but these last two only suggest a non persistent and non shareable UUID (user unique id)... which is fine for certain in-app needs, but not at all a replacement for the former persistent and shareable UDID (unique device id).

As for any scheme based on the MAC address and/or bundle-id, it's either too sensitive (see many discussions elsewhere on this topic) or not universal enough.

This issue #17 is ONLY about corner cases where OpenUDID is in fact duplicate because of the persistence across restores on different "active devices". I will close this topic since there is consensus on how to solve this.
