### ISSUE TITLE
OpenUDID doesn't work on iOS 7

### ISSUE THREAD

**Issue by runaway518** [ylechelle/OpenUDID#53]
I have an application use OpenUDID on iOS 7. After installing the application, my UDID is AAAAA but after reinstalling, it's BBBBBB, they are not the same! But with iOS6 or less, they are the same!

**Comment by ylechelle** [comment]
First of all, I do not recommend that you use OpenUDID on iOS 7 (see note that it is now deprecated and will no longer be supported). That being said, your issue is possibly directly related to the fact that you had one single app depending on OpenUDID on your device, then was removed which cleared all traces of OpenUDID on that device, and therefore a new token was recreated afterwards. OpenUDID is persistent only when at least one app using it remains on the device.
