### ISSUE TITLE
Possibility of compromising OpenUDID

### ISSUE THREAD

**Issue by grantland** [ylechelle/OpenUDID#9]
It seems that both SecureUDID and OpenUDID have a possibility of a third party modifying the base UID that both libraries rely on and compromising the SecureUDID/OpenUDID.

A third party could write a paste a pasteboard with the same format and with the same naming schema. If the third party app was installed before any OpenUDID apps were installed (or if there was just one OpenUDID app), valid OpenUDID apps installed after would copy the base UID the third party created as a valid OpenUDID.

The best solution might be providing a closed source library that uses a signature to sign and validate valid pasteboards.

**Comment by ylechelle** [comment]
Actually, if that "fraudulent" base UID is random, then it works just the same!
OpenUDID only needs some form of random string with little possible collision.
A fraudulent app would have to be pretty popular and widespread to preempt other valid OpenUDID hosts.
A closed source library could always be hijacked/hacked, and would not comfort most developers who need full disclosure and transparency. OpenUDID wins if enough apps adopt it - it will be stronger as more apps adopt it, exponentially so.
If that's not the case, then it's not worth pursuing this effort.

I need to check what SecureUDID is really about. From what I gather, it's an offspring of OpenUDID largely inspired by OpenUDID and not in the spirit of this initial project. The authors should have joined the effort/discussion and contribute to this one instead of adding further confusion... which is the last thing we need for persistent and cross-app UID sharing!

**Comment by grantland** [comment]
Yeah it seems SecureUDID only works for your apps and not all SecureUDID apps.

In terms of the "fraudulent" base UID, the third party could make it a hardcoded value so all OpenUDIDs are the same. It's a possibility and any possibility when creating an identification library is bad.

The frequency is a really good safeguard though.

**Comment by ylechelle** [comment]
This was the only way I could think of that would not rely on a central and authoritative repository. We have to hope that the positive forces are stronger than the destructive ones ;-)
